# Generated by Django 6.0.3 on 2026-03-06 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cups', models.CharField(help_text="Ej: '903895'", max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaEquipoSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipo_origen', models.CharField(help_text="Ej: 'URIT-500C'", max_length=100)),
                ('codigo_barras_leido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('trama_cruda', models.TextField(help_text='Evidencia de la cadena original')),
                ('datos_json', models.JSONField(help_text='Datos parseados en estructura clave-valor')),
                ('procesado', models.BooleanField(default=False, help_text='Indica si ya se extrajo hacia resultado_analito')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenLaboratorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('observaciones_clinicas', models.TextField(blank=True, null=True)),
                ('estado_general', models.CharField(choices=[('Registrada', 'Registrada'), ('En Proceso', 'En Proceso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Registrada', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MuestraFisica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('tipo_muestra', models.CharField(help_text="Ej: 'Sangre Total', 'Orina'", max_length=50)),
                ('fecha_recoleccion', models.DateTimeField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='laboratorio.ordenlaboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenSolicitado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_examen', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Muestra Recolectada', 'Muestra Recolectada'), ('En Análisis', 'En Análisis'), ('Validado', 'Validado')], default='Pendiente', max_length=30)),
                ('cups', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laboratorio.catalogocups')),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes', to='laboratorio.muestrafisica')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_solicitados', to='laboratorio.ordenlaboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PA', 'Pasaporte'), ('MS', 'Menor sin Identificación'), ('AS', 'Adulto sin Identificación'), ('PEP', 'Permiso Especial de Permanencia'), ('PPT', 'Permiso de Protección Temporal')], max_length=3)),
                ('numero_documento', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo_biologico', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='unique_documento_paciente')],
            },
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='laboratorio.paciente'),
        ),
        migrations.CreateModel(
            name='ParametroExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parametro', models.CharField(help_text="Ej: 'Leucocitos'", max_length=100)),
                ('unidades_medida', models.CharField(blank=True, help_text="Ej: 'cel/uL'", max_length=20, null=True)),
                ('rango_referencia_minimo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rango_referencia_maximo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rango_texto', models.CharField(blank=True, help_text="Para valores cualitativos (Ej: 'Negativo')", max_length=100, null=True)),
                ('cups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='laboratorio.catalogocups')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAnalito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_resultado', models.CharField(max_length=100)),
                ('es_anormal', models.BooleanField(default=False)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('examen_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='laboratorio.examensolicitado')),
                ('lectura_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorio.lecturaequiposerial')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laboratorio.parametroexamen')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parametroexamen',
            constraint=models.UniqueConstraint(fields=('cups', 'nombre_parametro'), name='unique_parametro_por_cups'),
        ),
        migrations.AddConstraint(
            model_name='resultadoanalito',
            constraint=models.UniqueConstraint(fields=('examen_solicitado', 'parametro'), name='unique_resultado_parametro_examen'),
        ),
    ]
