# Generated by Django 6.0.3 on 2026-03-18 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Analizador Hematológico Mindray BC-5000', max_length=100)),
                ('codigo_equipo', models.CharField(help_text='Identificador único del equipo', max_length=30, unique=True)),
                ('tipo_conexion', models.CharField(choices=[('SERIAL', 'Puerto Serial RS-232/USB'), ('TCP', 'Red TCP/IP (LIS)')], default='SERIAL', max_length=10)),
                ('host_ip', models.CharField(blank=True, help_text='Dirección IP del equipo (solo para conexión TCP).', max_length=50, null=True)),
                ('puerto', models.CharField(help_text="Baudrate (ej: '9600') para Serial, o número de puerto TCP (ej: '5000').", max_length=20)),
                ('protocolo', models.CharField(choices=[('HL7', 'HL7 v2.x'), ('ASTM', 'ASTM E1381/E1394'), ('JSON', 'JSON propietario'), ('CSV', 'CSV / texto plano')], default='HL7', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('endpoint_destino', models.CharField(default='/api/v1/lecturas-serial/', help_text='Endpoint del backend al que el middleware debe enviar las tramas.', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de Equipo',
                'verbose_name_plural': 'Configuraciones de Equipos',
                'db_table': 'configuracion_equipo_Lab',
            },
        ),
        migrations.CreateModel(
            name='EstadoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'estado_muestra_Lab',
            },
        ),
        migrations.CreateModel(
            name='InformeResultados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF del informe generado.', null=True, upload_to='informes/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('hash_documento', models.CharField(blank=True, help_text='SHA-256 del contenido del PDF (garantía de inmutabilidad).', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Informe de Resultados',
                'verbose_name_plural': 'Informes de Resultados',
                'db_table': 'informe_resultados_Lab',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('resultado_listo', 'Resultado Listo'), ('muestra_rechazada', 'Muestra Rechazada'), ('examen_rechazado', 'Examen Rechazado'), ('alerta_critica', 'Alerta de Valor Crítico'), ('orden_finalizada', 'Orden Finalizada')], max_length=30)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion_Lab',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='parametroexamen',
            name='unique_parametro_por_cups',
        ),
        migrations.AddField(
            model_name='examensolicitado',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el bacteriólogo validó el examen.', null=True),
        ),
        migrations.AddField(
            model_name='examensolicitado',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo de rechazo. Se llena al rechazar el resultado.', null=True),
        ),
        migrations.AddField(
            model_name='examensolicitado',
            name='validado_por',
            field=models.ForeignKey(blank=True, help_text='Bacteriólogo que validó y firmó el resultado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='muestrafisica',
            name='condicion_muestra',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Hemolizada', 'Hemolizada'), ('Lipemica', 'Lipémica'), ('Icterica', 'Ictérica'), ('Insuficiente', 'Volumen insuficiente'), ('Coagulada', 'Coagulada'), ('Contaminada', 'Contaminada')], default='Normal', help_text='Condición visual de la muestra al analizarla.', max_length=20),
        ),
        migrations.AddField(
            model_name='muestrafisica',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo de rechazo si la muestra fue rechazada por el bacteriólogo.', null=True),
        ),
        migrations.AddField(
            model_name='muestrafisica',
            name='usuario_recolecta',
            field=models.ForeignKey(blank=True, help_text='Auxiliar de enfermería / flebotomista que tomó la muestra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_recolectadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='codigo_cie10',
            field=models.CharField(blank=True, help_text='Código diagnóstico CIE-10 del médico solicitante.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='convenio',
            field=models.CharField(blank=True, help_text='Convenio / aseguradora / EPS del paciente.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='entidad_remitente',
            field=models.CharField(blank=True, help_text='Entidad o institución que remite al paciente.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='fecha_admision',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora en que el paciente fue admitido en recepción del laboratorio.', null=True),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='medico',
            field=models.ForeignKey(blank=True, help_text='Médico que genera la orden clínica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='usuario_admite',
            field=models.ForeignKey(blank=True, help_text='Auxiliar/recepcionista que gestionó la admisión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_admitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parametroexamen',
            name='edad_maxima_anios',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Edad máxima del paciente (inclusive) en años. Vacío = sin límite superior.', null=True),
        ),
        migrations.AddField(
            model_name='parametroexamen',
            name='edad_minima_anios',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Edad mínima del paciente (inclusive) en años. Vacío = sin límite inferior.', null=True),
        ),
        migrations.AddField(
            model_name='parametroexamen',
            name='rango_panico_maximo',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Valor crítico superior: requiere alerta inmediata al médico.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parametroexamen',
            name='rango_panico_minimo',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Valor crítico inferior: requiere alerta inmediata al médico.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parametroexamen',
            name='sexo_aplica',
            field=models.ForeignKey(blank=True, help_text='Deje en blanco si el rango aplica para ambos sexos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametros', to='laboratorio.sexobiologico'),
        ),
        migrations.AddField(
            model_name='resultadoanalito',
            name='comentario_bacteriologo',
            field=models.TextField(blank=True, help_text='Observación clínica del bacteriólogo sobre este analito (FASE 5).', null=True),
        ),
        migrations.AddField(
            model_name='resultadoanalito',
            name='es_critico',
            field=models.BooleanField(default=False, help_text='True si el valor supera los rangos de pánico definidos en ParametroExamen.'),
        ),
        migrations.AlterField(
            model_name='lecturaequiposerial',
            name='datos_json',
            field=models.JSONField(help_text='Datos parseados en estructura clave-valor.'),
        ),
        migrations.AlterField(
            model_name='lecturaequiposerial',
            name='procesado',
            field=models.BooleanField(default=False, help_text='True cuando los analitos ya fueron extraídos a ResultadoAnalito.'),
        ),
        migrations.AlterField(
            model_name='lecturaequiposerial',
            name='trama_cruda',
            field=models.TextField(help_text='Evidencia de la cadena original enviada por el equipo.'),
        ),
        migrations.AlterField(
            model_name='ordenlaboratorio',
            name='numero_orden',
            field=models.CharField(blank=True, help_text='Auto-generado si no se proporciona. Formato: LAB-YYYYMMDD-NNNN', max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name='catalogocups',
            table='catalogo_cups_Lab',
        ),
        migrations.AlterModelTable(
            name='examensolicitado',
            table='examen_solicitado_Lab',
        ),
        migrations.AlterModelTable(
            name='lecturaequiposerial',
            table='lectura_equipo_serial_Lab',
        ),
        migrations.AlterModelTable(
            name='muestrafisica',
            table='muestra_fisica_Lab',
        ),
        migrations.AlterModelTable(
            name='ordenlaboratorio',
            table='orden_laboratorio_Lab',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='paciente_Lab',
        ),
        migrations.AlterModelTable(
            name='parametroexamen',
            table='parametro_examen_Lab',
        ),
        migrations.AlterModelTable(
            name='resultadoanalito',
            table='resultado_analito_Lab',
        ),
        migrations.AddField(
            model_name='muestrafisica',
            name='estado_muestra',
            field=models.ForeignKey(blank=True, help_text='Estado actual de la muestra en el flujo pre-analítico.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='muestras', to='laboratorio.estadomuestra'),
        ),
        migrations.AddField(
            model_name='informeresultados',
            name='generado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informeresultados',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='laboratorio.ordenlaboratorio'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='laboratorio.ordenlaboratorio'),
        ),
    ]
