# Generated by Django 6.0.3 on 2026-03-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_configuracionequipo_estadomuestra_informeresultados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionequipo',
            name='token_middleware',
            field=models.CharField(blank=True, help_text='Token estático compartido con el middleware para autenticación de ingesta serial.', max_length=80, null=True, unique=True),
        ),
    ]
