# Generated by Django 6.0.3 on 2026-05-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_add_token_middleware'),
        ('usuarios', '0002_alter_usuario_numero_id_alter_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='causa_externa',
            field=models.CharField(choices=[('Accidente de trabajo', 'Accidente de trabajo'), ('Accidente de transito', 'Accidente de tránsito'), ('Accidente rabico', 'Accidente rábico'), ('Accidente ofidico', 'Accidente ofídico'), ('Otro tipo de accidente', 'Otro tipo de accidente'), ('Evento catastrofico', 'Evento catastrófico'), ('Lesion por agresion', 'Lesión por agresión'), ('Lesion auto infligida', 'Lesión auto infligida'), ('Sospecha maltrato fisico', 'Sospecha maltrato físico'), ('Sospecha abuso sexual', 'Sospecha abuso sexual'), ('Sospecha violencia sexual', 'Sospecha violencia sexual'), ('Sospecha maltrato emocional', 'Sospecha maltrato emocional'), ('Enfermedad general', 'Enfermedad general'), ('Enfermedad profesional', 'Enfermedad profesional'), ('Otra', 'Otra')], default='Enfermedad general', max_length=40),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='finalidad_consulta',
            field=models.CharField(choices=[('Atencion Parto', 'Atención Parto'), ('Atencion Recien Nacido', 'Atención Recién Nacido'), ('Atencion Planificacion Familiar', 'Planificación Familiar'), ('Deteccion Alteraciones Crecimiento', 'Crecimiento y Desarrollo'), ('Deteccion Alteraciones Joven', 'Detección Joven'), ('Deteccion Alteraciones Embarazo', 'Detección Embarazo'), ('Deteccion Alteraciones Adulto', 'Detección Adulto'), ('Deteccion Alteraciones Agudeza Visual', 'Agudeza Visual'), ('Deteccion Enfermedad Profesional', 'Enf. Profesional'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=40),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='tipo_diagnostico',
            field=models.CharField(choices=[('Impresion diagnostica', 'Impresión diagnóstica'), ('Confirmado nuevo', 'Confirmado nuevo'), ('Confirmado repetido', 'Confirmado repetido')], default='Impresion diagnostica', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimiento_habeas_data',
            field=models.BooleanField(default=False, help_text='Indica si el paciente aceptó el tratamiento de datos personales.'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='departamento_residencia',
            field=models.ForeignKey(blank=True, help_text='Departamento de residencia del paciente (DIVIPOLA).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='usuarios.departamento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='municipio_residencia',
            field=models.ForeignKey(blank=True, help_text='Municipio de residencia del paciente (DIVIPOLA).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='usuarios.municipio'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='regimen_salud',
            field=models.CharField(choices=[('Contributivo', 'Contributivo'), ('Subsidiado', 'Subsidiado'), ('Vinculado', 'Vinculado'), ('Particular', 'Particular'), ('Otro', 'Otro')], default='Particular', help_text='Régimen de afiliación al sistema de salud.', max_length=20),
        ),
    ]
